config/routes.rb
ControleAIT::Application.routes.draw do
  resources :autos

  resources :agents
  
  get 'report' => 'autos#report',:as => 'report'

  root :to => 'autos#index'

end

app/models/agent.rb
#encoding: utf-8
class Agent < ActiveRecord::Base
	validates :nome,  
						:presence => true, 
						:length => { :maximum => 200 }
	
	validates :mat,  
						:presence => true, 
						:uniqueness => true, 
						:length => { :maximum => 30 }
						
	has_many :autos, :dependent => :destroy

	def destroy
		return false if autos.any?
		super
	end	

end

app/models/auto.rb
class Auto < ActiveRecord::Base
	validates :agent,  
						:presence => true
						
	validates :inicio, :fim, 
						:allow_blank => true,
						:numericality => { :only_integer => true },
						:format => { :with => /\A[+]?\d+\Z/ , :message => "Somente inteiros positivos"},
						:length => { :maximum => 25 }

	
  belongs_to :agent
  
	def self.search(search, page)
 	 if search
  	  find(:all, :conditions => ['data_do_cadastro LIKE ?', "%#{search}%"], :order => "inicio")
  	else
  	  find(:all)
  	end
  	
	  paginate :per_page => 50, :page => page,
             :conditions => ['data_do_cadastro like ?', "%#{search}%"],
             :order => 'inicio'	
  	
	end
	
  validate :inicio_fim_valid

   def inicio_fim_valid
     errors.add(:inicio, " não deve ser menor que inicio") if self.inicio < self.fim
   end

end

app/controllers/agents_controller.rb
class AgentsController < ApplicationController
  # GET /agents
  # GET /agents.json
  def index
    @agents = Agent.order("nome").paginate :page => params['page'], :per_page => 50

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @agents }
    end
  end

  # GET /agents/1
  # GET /agents/1.json
  def show
    @agent = Agent.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @agent }
    end
  end

  # GET /agents/new
  # GET /agents/new.json
  def new
    @agent = Agent.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @agent }
    end
  end

  # GET /agents/1/edit
  def edit
    @agent = Agent.find(params[:id])
  end

  # POST /agents
  # POST /agents.json
  def create
    @agent = Agent.new(params[:agent])

    respond_to do |format|
      if @agent.save
        format.html { redirect_to @agent, notice: 'Agent was successfully created.' }
        format.json { render json: @agent, status: :created, location: @agent }
      else
        format.html { render action: "new" }
        format.json { render json: @agent.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /agents/1
  # PUT /agents/1.json
  def update
    @agent = Agent.find(params[:id])

    respond_to do |format|
      if @agent.update_attributes(params[:agent])
        format.html { redirect_to @agent, notice: 'Agent was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @agent.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /agents/1
  # DELETE /agents/1.json
  def destroy
    @agent = Agent.find(params[:id])
    @agent.destroy

    respond_to do |format|
      format.html { redirect_to agents_url }
      format.json { head :ok }
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/autos_controller.rb
class AutosController < ApplicationController
  # GET /autos
  # GET /autos.json
  def index
    @autos = Auto.search(params[:search], params[:page])
   
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @autos }
    end
  end

  # GET /autos/1
  # GET /autos/1.json
  def show
    @auto = Auto.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @auto }
    end
  end

  # GET /autos/new
  # GET /autos/new.json
  def new
    @auto = Auto.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @auto }
    end
  end

  # GET /autos/1/edit
  def edit
    @auto = Auto.find(params[:id])
  end

  # POST /autos
  # POST /autos.json
  def create
    @auto = Auto.new(params[:auto])

    respond_to do |format|
      if @auto.save
        format.html { redirect_to @auto, notice: 'Auto was successfully created.' }
        format.json { render json: @auto, status: :created, location: @auto }
      else
        format.html { render action: "new" }
        format.json { render json: @auto.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /autos/1
  # PUT /autos/1.json
  def update
    @auto = Auto.find(params[:id])

    respond_to do |format|
      if @auto.update_attributes(params[:auto])
        format.html { redirect_to @auto, notice: 'Auto was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @auto.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /autos/1
  # DELETE /autos/1.json
  def destroy
    @auto = Auto.find(params[:id])
    @auto.destroy

    respond_to do |format|
      format.html { redirect_to autos_url }
      format.json { head :ok }
    end
  end
  def report
    @autos = Auto.find(:all, :conditions => ['data_do_cadastro = ?', params[:search] ], :order => "inicio")
  end 
  
end

app/helpers/agents_helper.rb
module AgentsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/autos_helper.rb
module AutosHelper
end

app/views/agents/_form.html.erb
<%= form_for(@agent) do |f| %>
  <% if @agent.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@agent.errors.count, "erro") %> impedindo esse agente de ser salvo:</h2>

      <ul>
      <% @agent.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nome %><br />
    <%= f.text_field :nome %>
  </div>
  <div class="field">
    <%= f.label :mat %><br />
    <%= f.text_field :mat %>
  </div>
  <div class="field">
    <%= f.label :turno %><br />
    <%= f.select(:turno, [['Manhã'],['Tarde'],['Noite']])  %>

  </div>
  <div class="actions">
    <%= f.submit :class => "btn success" %>
  </div>
<% end %>

app/views/agents/edit.html.erb
<h1>Editando gentes</h1>

<%= render 'form' %>

<%= link_to 'Mostrar', @agent, :class => "label" %> |
<%= link_to 'Voltar', agents_path, :class => "label" %>

app/views/agents/index.html.erb
<h1>Listando agentes</h1>

<table>
  <tr class="blue">
    <th>Nome</th>
    <th>Mat</th>
    <th>Turno</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @agents.each do |agent| %>
  <tr>
    <td><%= agent.nome %></td>
    <td><%= agent.mat %></td>
    <td><%= agent.turno %></td>
    <td><%= link_to 'Mostrar', agent, :class => "label" %></td>
    <td><%= link_to 'Editar', edit_agent_path(agent), :class => "label" %></td>
    <td><%= link_to 'Deletar', agent, confirm: 'Tem certeza?', method: :delete, :class => "label" %></td>
  </tr>
<% end %>
</table>

<%= will_paginate @agents %>

<br />

<%= link_to 'Cadastrar Agente', new_agent_path, :class => "label notice" %>

app/views/agents/new.html.erb
<h1>Cadastrar Novo agente</h1>

<%= render 'form' %>

<%= link_to 'Voltar', agents_path, :class => "label" %>

app/views/agents/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Nome:</b>
  <%= @agent.nome %>
</p>

<p>
  <b>Mat:</b>
  <%= @agent.mat %>
</p>

<p>
  <b>Turno:</b>
  <%= @agent.turno %>
</p>


<%= link_to 'Editar', edit_agent_path(@agent), :class => "label" %> |
<%= link_to 'Voltar', agents_path, :class => "label" %>

app/views/autos/_form.html.erb
<%= form_for(@auto) do |f| %>
  <% if @auto.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@auto.errors.count, "erro") %> impedindo esse(s) auto(s) de ser salvo:</h2>

      <ul>
      <% @auto.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :agent %><br />
   	<%= f.collection_select(:agent_id, Agent.order('nome'), :id, :nome, {:prompt => true})%>
  </div>
  <div class="field">
    <%= f.label :inicio %><br />
    <%= f.number_field :inicio %>
  </div>
  <div class="field">
    <%= f.label :fim %><br />
    <%= f.number_field :fim %>
  </div>
  <div class="field">
    <%= f.label :validade %><br />
    <%= f.select(:validade, [['Válido'],['Inválido']])  %>
  </div>
  <div class="field">
    <%= f.label :data_da_infracao %><br />
    <%= f.date_select :data_da_infracao %>
  </div>
  <div class="field">
    <%= f.label :data_do_cadastro %><br />
    <%= f.date_select :data_do_cadastro %>
  </div>
  <div class="actions">
    <%= f.submit :class => "btn success" %>
  </div>
<% end %>

app/views/autos/edit.html.erb
<h1>Editando auto(s)</h1>

<%= render 'form' %>

<%= link_to 'Mostrar', @auto, :class => "label" %> |
<%= link_to 'Voltar', autos_path, :class => "label" %>

app/views/autos/index.html.erb
<%= form_tag autos_path, :method => 'get' do %>
	<p>
		<%= text_field_tag :search, params[:search] %>
		<%= submit_tag "Search", :name => nil, :class => "btn success" %>
	</p>
<% end %>
<% @autos.each do |auto| %>
<% @data = auto.data_do_cadastro %>
<% end %>

<center><h4>Controle de AIT's realizado no dia 
<% if @autos == Auto.all %>
<%= @data = nil %>
<% else %>
<%= @data.strftime("%d/%m/%Y") %>
<% end %>
</h4></center>
<% @total_validos = 0 %>
<% @total_invalidos = 0 %>
<% @total_validos_manha = 0 %>
<% @total_invalidos_manha = 0 %>
<% @total_validos_tarde = 0 %>
<% @total_invalidos_tarde = 0 %>
<% @total_validos_noite = 0 %>
<% @total_invalidos_noite = 0 %>

<table>
  <tr class="blue">
    <th>Mat</th>
    <th>Agente</th>
    <th>Início</th>
    <th>Fim</th>
    <th>Validade</th>
    <th>Data da infração</th>
    <th>Total</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @autos.each do |auto| %>
	<% @data = auto.data_do_cadastro %>
	<% if auto.validade == "Válido" %>
		<% @total_validos += auto.fim - auto.inicio + 1 %>
	<% elsif auto.validade == "Inválido" %>
		<% @total_invalidos += auto.fim - auto.inicio + 1 %>
	<% end %>

	<% if auto.validade == "Válido" and auto.agent.turno == "Manhã" %>
		<% @total_validos_manha += auto.fim - auto.inicio + 1 %>
	<% elsif auto.validade == "Inválido" and auto.agent.turno == "Manhã" %>
		<% @total_invalidos_manha += auto.fim - auto.inicio + 1 %>
	<% end %>

	<% if auto.validade == "Válido" and auto.agent.turno == "Tarde" %>
		<% @total_validos_tarde += auto.fim - auto.inicio + 1 %>
	<% elsif auto.validade == "Inválido" and auto.agent.turno == "Tarde" %>
		<% @total_invalidos_tarde += auto.fim - auto.inicio + 1 %>
	<% end %>

	<% if auto.validade == "Válido" and auto.agent.turno == "Noite" %>
		<% @total_validos_noite += auto.fim - auto.inicio + 1 %>
	<% elsif auto.validade == "Inválido" and auto.agent.turno == "Noite" %>
		<% @total_invalidos_noite += auto.fim - auto.inicio + 1 %>
	<% end %>

	
  <tr>
    <td><%= auto.agent.mat %></td>
    <td><%= auto.agent.nome %></td>
    <td><%= auto.inicio %></td>
    <td><%= auto.fim %></td>
    <td><%= auto.validade %></td>
    <td><%=l  auto.data_da_infracao, :format => :default %></td>
    <td><%= auto.fim - auto.inicio + 1 %></td>
    <td><%= link_to 'Mostrar', auto, :class => "label" %></td>
    <td><%= link_to 'Editar', edit_auto_path(auto), :class => "label" %></td>
    <td><%= link_to 'Deletar', auto, confirm: 'Tem certeza?', method: :delete, :class => "label" %></td>
  </tr>
<% end %>
</table>

<%= will_paginate @autos %>

<style type="text/css">
  #block3 {
		display: none; }
</style>
 
<a href="#" id="for-block3"><b>Relatório Turnos</b></a>
<div id="block3">
<table>
<tr class="blue">
    <th>DATA 
    	<% if @autos == Auto.all %>
			<%= @data = nil %>
			<% else %>
			<%= @data.strftime("%d/%m/%Y") %>
			<% end %>
		</th>
    <th>Válidos</th>
    <th>Inválidos</th>
    <th>Total</th>
</tr>
<tr>
	<td class="blue">Autos Lavrados <b>MANHÃ</b></td>
	<td> <%= @total_validos_manha %></td>
	<td> <%= @total_invalidos_manha %></td>
	<td> <%= @total_validos_manha + @total_invalidos_manha  %></td>
</tr>
<tr>
	<td class="blue">Autos Lavrados <b>TARDE</b></td>
	<td> <%= @total_validos_tarde %></td>
	<td> <%= @total_invalidos_tarde %></td>
	<td> <%= @total_validos_tarde + @total_invalidos_tarde  %></td>
</tr>
<tr>
	<td class="blue">Autos Lavrados <b>NOITE</b></td>
	<td> <%= @total_validos_noite %></td>
	<td> <%= @total_invalidos_noite %></td>
	<td> <%= @total_validos_noite + @total_invalidos_noite  %></td>
</tr>
<tr>
	<td><b class="blue">Total Geral</b></td>
	<td> <%= @total_validos %></td>
	<td> <%= @total_invalidos %></td>
	<td> <%= @total_validos + @total_invalidos %></td>
</tr>
</table>
</div>

<br /><br />
<%= link_to 'Cadastrar Auto(s)', new_auto_path, :class => "label notice" %>
<br /><br />

app/views/autos/new.html.erb
<h1>Cadastrar auto(s)</h1>

<%= render 'form' %>

<%= link_to 'Voltar', autos_path, :class => "label" %>

app/views/autos/report.html.erb
<%= form_tag '#report', :method => 'get' do %>
	<p>
		<%= text_field_tag :search, params[:search] %>
		<%= submit_tag "Search", :name => nil, :class => "btn success" %>
	</p>
<% end %>
<% @autos.each do |auto| %>
<% @data = auto.data_do_cadastro %>
<% end %>

<center><h4>Controle de AIT realizado no dia 
<% if @autos == Auto.all %>
<%= @data = nil %>
<% else %>
<% if @data != nil %>
<%= @data.strftime("%d/%m/%Y") %>
<% end %>
<% end %>
</h4></center>

<% @cont = 0 %>
<% @datateste = nil %>
<table>
  <tr class="blue">
    <th>Ordem</th>
    <th>Nº AIT</th>
    <th>DATA</th>
    <th>Ordem</th>
    <th>Nº AIT</th>
    <th>DATA</th>
    <th>Ordem</th>
    <th>Nº AIT</th>
    <th>DATA</th>
  </tr>
  <tr>
<% @autos.each do |auto| %>

  <% if auto.inicio == auto.fim and auto.validade == "Válido" %>
		<% @cont += 1 %>
		<% if (@cont - 1 ) % 3 == 0 %>
			<tr>
			</tr>
		<% end %>
    <td><%= @cont %></td>
    <td><%= auto.inicio %></td>
    <td><%=l  auto.data_da_infracao, :format => :default %></td>
	<% elsif auto.inicio != auto.fim and auto.validade == "Válido" %>
		<% for i in (auto.inicio..auto.fim) %>
		<% @cont += 1 %>
		<% if (@cont - 1 ) % 3 == 0 %>
			</tr>
			<tr>
		<% end %>

    <td><%= @cont %></td>
    <td><%= i %></td>
    <td><%=l  auto.data_da_infracao, :format => :default %></td>
		<% end %>
	<% end %>	

<% end %>

  </tr>
</table>

&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp <b>Inválidos:</b> &nbsp&nbsp
<font class="red">
<% @autos.each do |auto| %>
  <% if auto.inicio == auto.fim and auto.validade == "Inválido" %>
		<%= auto.inicio %>&nbsp&nbsp
	<% elsif auto.inicio != auto.fim and auto.validade == "Inválido" %>
		<% for i in (auto.inicio..auto.fim) %>
			<%= i %>&nbsp&nbsp
		<% end %>
	<% end %>
	<% @datateste = auto.data_da_infracao %>
<% end %>
</font>
<br /><br />

<style type="text/css">
  #block3 {
		display: none; }
</style>
 
<a href="#" id="for-block3"><b>Relatório Quantidade de Autos por Data da Infração</b></a>
<div id="block3">
<table>
<tr>
<% @cont = 0 %>
<% @cont_tr = 0 %>
<% @autos.reverse.each do |auto| %>
	<% @cont_tr += 1 %>

	<% if auto.data_da_infracao == @datateste %>	

	  <% if auto.inicio == auto.fim %>
			<% @cont += 1 %>
		<% elsif auto.inicio != auto.fim %>
			<% @cont += auto.fim - auto.inicio + 1 %>
		<% end %>	

	<% else %>	
			<td><%= @datateste.strftime("%d/%m/%Y") %></td><td><%= @cont %></td>
		<% @datateste = auto.data_da_infracao %>
		<% @cont = 0 %>
	  <% if auto.inicio == auto.fim %>
			<% @cont += 1 %>
		<% elsif auto.inicio != auto.fim %>
			<% @cont += auto.fim - auto.inicio + 1 %>
		<% end %>	
	<% end %>	
	<% if (@cont_tr-1) % 5 == 0 %>
		</tr><tr>
	<% end %>
<% end %>
	<% if @datateste != nil %>
		<td><%= @datateste.strftime("%d/%m/%Y") %></td><td><%= @cont %></td>
			<% end %>
<tr>
</table>
</div>
<br /><br />

app/views/autos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Agent:</b>
  <%= @auto.agent.nome %>
</p>

<p>
  <b>Inicio:</b>
  <%= @auto.inicio %>
</p>

<p>
  <b>Fim:</b>
  <%= @auto.fim %>
</p>

<p>
  <b>Validade:</b>
  <%= @auto.validade %>
</p>

<p>
  <b>Data da infracao:</b>
  <%=l  @auto.data_da_infracao, :format => :default %>
</p>

<p>
  <b>Data de entrega:</b>
  <%=l  @auto.data_do_cadastro, :format => :default %>
</p>


<%= link_to 'Editar', edit_auto_path(@auto), :class => "label" %> |
<%= link_to 'Voltar', autos_path, :class => "label" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ControleAIT</title>
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>

<script>
<!--
$(function(){
    $("#for-block3")
        .click(function(){
       $("#block3").toggle();
    });
            
});
//-->
</script>


</head>
<body>

<div class="container">

 <div class="topbar" >
      <div class="topbar-inner">
        <div class="container">
          <a class="brand" href="#">Controle de AIT's</a>
          <ul class="nav">
            <li><a href="/agents">Agentes</a></li>
            <li><a href="/autos">Autos</a></li>
            <li><a href="/report">Relatório</a></li>
          </ul>

        </div>
      </div>
    </div>
<br /><br /><br />


<%= yield %>

</div>
</body>
</html>